//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CYJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHART
    {
        public int chartID { get; set; }
        public Nullable<int> teamID { get; set; }
        public Nullable<int> workstreamID { get; set; }
        public Nullable<int> categoryID { get; set; }
        public Nullable<int> subcategoryID { get; set; }
        public Nullable<int> fiscalYearID { get; set; }
        public Nullable<int> quarteroptionID { get; set; }
        public Nullable<int> goalActualID { get; set; }
        public Nullable<int> Xaxis { get; set; }
        public Nullable<int> Yaxis { get; set; }
        public string chartName { get; set; }
    
        public virtual CATEGORY CATEGORY { get; set; }
        public virtual FISCALYEAR FISCALYEAR { get; set; }
        public virtual GOALACTUAL GOALACTUAL { get; set; }
        public virtual QUARTEROPTION QUARTEROPTION { get; set; }
        public virtual SUBCATEGORY SUBCATEGORY { get; set; }
        public virtual TEAM TEAM { get; set; }
        public virtual TEAM TEAM1 { get; set; }
        public virtual WORKSTREAM WORKSTREAM { get; set; }
        public virtual WORKSTREAM WORKSTREAM1 { get; set; }
    }
}
