//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CYJ.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class WORKSTREAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WORKSTREAM()
        {
            this.CATEGORies = new HashSet<CATEGORY>();
            this.CHARTs = new HashSet<CHART>();
            this.CHARTs1 = new HashSet<CHART>();
            this.GOALACTUALs = new HashSet<GOALACTUAL>();
            this.GOALACTUALs1 = new HashSet<GOALACTUAL>();
        }

        [Display(Name = "Workstream")]
        public int workstreamID { get; set; }
        [Display(Name = "Workstream")]
        public string workstreamName { get; set; }
        [Display(Name = "Team")]
        public Nullable<int> teamID { get; set; }
        [Display(Name = "Category")]
        public Nullable<int> categoryID { get; set; }
        [Display(Name = "Subcategory")]
        public Nullable<int> subcategoryID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CATEGORY> CATEGORies { get; set; }
        public virtual CATEGORY CATEGORY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHART> CHARTs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHART> CHARTs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GOALACTUAL> GOALACTUALs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GOALACTUAL> GOALACTUALs1 { get; set; }
        public virtual SUBCATEGORY SUBCATEGORY { get; set; }
        public virtual TEAM TEAM { get; set; }
    }
}
